/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio;

import javax.swing.JOptionPane;

/**
 *
 * @author Francisco Diaz
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        JMSalir = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jMAAgregar = new javax.swing.JMenuItem();
        jMCursos = new javax.swing.JMenu();
        jMCAgregar = new javax.swing.JMenuItem();
        jMCListar = new javax.swing.JMenuItem();
        JMGESTIONESCOLAR = new javax.swing.JMenu();
        JMGESALUMNO = new javax.swing.JMenuItem();
        JMConsultarAlumno = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMGESTIONESCOLAR1 = new javax.swing.JMenu();
        JMGESALUMNO1 = new javax.swing.JMenuItem();
        JMConsultarAlumno1 = new javax.swing.JMenuItem();
        JMGESTIONESCOLAR2 = new javax.swing.JMenu();
        JMGESALUMNO2 = new javax.swing.JMenuItem();
        JMConsultarAlumno2 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLICACIÓN COLEGIO ADSI 1438222");
        setBackground(new java.awt.Color(204, 255, 204));
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio/Imagenes/COLEGIO TLAQUILTZINAPA.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        JMSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JMSalir.setMinimumSize(new java.awt.Dimension(0, 4));

        jMAlumnos.setText("Alumnos");
        jMAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMAAgregar.setText("Agregar");
        jMAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAAgregarActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMAAgregar);

        JMSalir.add(jMAlumnos);

        jMCursos.setText("Cursos");
        jMCursos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMCAgregar.setText("Agregar");
        jMCAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAgregarActionPerformed(evt);
            }
        });
        jMCursos.add(jMCAgregar);

        jMCListar.setText("Gestio de curso");
        jMCListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCListarActionPerformed(evt);
            }
        });
        jMCursos.add(jMCListar);

        JMSalir.add(jMCursos);

        JMGESTIONESCOLAR.setText("Gestion Escolar");
        JMGESTIONESCOLAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JMGESALUMNO.setText("Gestión Alumno");
        JMGESALUMNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGESALUMNOActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR.add(JMGESALUMNO);

        JMConsultarAlumno.setText("Gestión Cursos");
        JMConsultarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConsultarAlumnoActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR.add(JMConsultarAlumno);

        jMenuItem1.setText("Gestión Calificación");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR.add(jMenuItem1);

        JMSalir.add(JMGESTIONESCOLAR);

        JMGESTIONESCOLAR1.setText("Capturar calificaciones");
        JMGESTIONESCOLAR1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JMGESALUMNO1.setText("Gestión Alumnos");
        JMGESALUMNO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGESALUMNO1ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR1.add(JMGESALUMNO1);

        JMConsultarAlumno1.setText("Borrar Todas las tablas");
        JMConsultarAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConsultarAlumno1ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR1.add(JMConsultarAlumno1);

        JMSalir.add(JMGESTIONESCOLAR1);

        JMGESTIONESCOLAR2.setText("Listar grupos");
        JMGESTIONESCOLAR2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JMGESALUMNO2.setText("Grupo1");
        JMGESALUMNO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGESALUMNO2ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR2.add(JMGESALUMNO2);

        JMConsultarAlumno2.setText("Grupo 2");
        JMConsultarAlumno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConsultarAlumno2ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR2.add(JMConsultarAlumno2);

        jMenuItem2.setText("Grupo 3");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR2.add(jMenuItem2);

        jMenuItem3.setText("Grupo 4");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR2.add(jMenuItem3);

        jMenuItem4.setText("Grupo 5");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR2.add(jMenuItem4);

        jMenuItem5.setText("Grupo 6");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        JMGESTIONESCOLAR2.add(jMenuItem5);

        JMSalir.add(JMGESTIONESCOLAR2);

        jMenu1.setText("Cerrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMSalir);

        JMSalir.add(jMenu1);

        setJMenuBar(JMSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAAgregarActionPerformed
        // TODO add your handling code here:
         Registra_Alumnos registra_Alumnos=new Registra_Alumnos();
        registra_Alumnos.setVisible(true);
        dispose(); 
       
    }//GEN-LAST:event_jMAAgregarActionPerformed

    private void jMCAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAgregarActionPerformed
        // TODO add your handling code here:
        Registro_curso curso=new Registro_curso();
        curso.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMCAgregarActionPerformed

    private void jMCListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCListarActionPerformed
        // TODO add your handling code here:
        Gestion_cursos gestion_cursos=new Gestion_cursos();
        gestion_cursos.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMCListarActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
       int confirmado = JOptionPane.showConfirmDialog(null, "Está seguro de Salir");
        if (JOptionPane.OK_OPTION==confirmado){
            LOGIN frm=new LOGIN();
       frm.setVisible(true);
        this.setVisible(false);
        }
     
       
    }//GEN-LAST:event_jMSalirActionPerformed

    private void JMGESALUMNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGESALUMNOActionPerformed
        // TODO add your handling code here:
        Gestion_alumnos gestion_alumnos=new Gestion_alumnos();
        gestion_alumnos.setVisible(true);
        dispose();
       
       
    }//GEN-LAST:event_JMGESALUMNOActionPerformed

    private void JMConsultarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConsultarAlumnoActionPerformed
        // TODO add your handling code here:
        Gestion_cursos gestion_cursos=new Gestion_cursos();
        gestion_cursos.setVisible(true);
        dispose();
            
        
    }//GEN-LAST:event_JMConsultarAlumnoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Gestion_calificaciones gestion_calificaciones=new Gestion_calificaciones();
        gestion_calificaciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMGESALUMNO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGESALUMNO1ActionPerformed
        // TODO add your handling code here:
          Gestion_alumnos gestion_alumnos=new Gestion_alumnos();
        gestion_alumnos.setVisible(true);
        dispose();
    }//GEN-LAST:event_JMGESALUMNO1ActionPerformed

    private void JMConsultarAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConsultarAlumno1ActionPerformed
        // TODO add your handling code here:
        Eliminar_tareas  eliminar_tareas=new Eliminar_tareas();
        eliminar_tareas.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_JMConsultarAlumno1ActionPerformed

    private void JMGESALUMNO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGESALUMNO2ActionPerformed
        // TODO add your handling code here:
        Grupo1 grupo=new Grupo1();
        grupo.setVisible(true);
        dispose();
    }//GEN-LAST:event_JMGESALUMNO2ActionPerformed

    private void JMConsultarAlumno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConsultarAlumno2ActionPerformed
        // TODO add your handling code here:
         Grupo2 grupo=new Grupo2();
        grupo.setVisible(true);
        dispose();
            
    }//GEN-LAST:event_JMConsultarAlumno2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Grupo3 grupo=new Grupo3();
        grupo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Grupo4 grupo=new Grupo4();
        grupo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Grupo5 grupo=new Grupo5();
        grupo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Grupo6 grupo=new Grupo6();
        grupo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMConsultarAlumno;
    private javax.swing.JMenuItem JMConsultarAlumno1;
    private javax.swing.JMenuItem JMConsultarAlumno2;
    private javax.swing.JMenuItem JMGESALUMNO;
    private javax.swing.JMenuItem JMGESALUMNO1;
    private javax.swing.JMenuItem JMGESALUMNO2;
    private javax.swing.JMenu JMGESTIONESCOLAR;
    private javax.swing.JMenu JMGESTIONESCOLAR1;
    private javax.swing.JMenu JMGESTIONESCOLAR2;
    private javax.swing.JMenuBar JMSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMAAgregar;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenuItem jMCAgregar;
    private javax.swing.JMenuItem jMCListar;
    private javax.swing.JMenu jMCursos;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
